---
development: &defaults
  # These are the settings for repository :default
  adapter:  sqlite3
  database: db/blinki_development.db
 
  # Add more repositories
  # repositories:
  #   repo1:
  #     adapter:  sqlite3
  #     database: sample_1_development.db
  #   repo2:
  #     ...
 
test:
  <<:       *defaults
  database: db/blinki_test.db
 
  # repositories:
  #   repo1:
  #     database: sample_1_test.db
 
production:
  <<:       *defaults
  database: db/blinki_production.db
 
  # repositories:
  #   repo1:
  #     database: sample_production.db
 
rake:
  <<: *defaults